// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi1.Models;

namespace webapi1.Migrations
{
    [DbContext(typeof(FoodContext))]
    partial class FoodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webapi1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Defig");

                    b.Property<DateTime>("InsertDate");

                    b.Property<int>("InsertId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<int>("UpdateId");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("webapi1.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Defig");

                    b.Property<DateTime>("InsertDate");

                    b.Property<int>("InsertId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<int>("UpdateId");

                    b.Property<int?>("categoryId");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("webapi1.Models.Food", b =>
                {
                    b.HasOne("webapi1.Models.Category", "category")
                        .WithMany("Foods")
                        .HasForeignKey("categoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
